"""followers

Revision ID: 95320c31ce4a
Revises: 1c895164b7fb
Create Date: 2018-02-24 12:23:33.978157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95320c31ce4a'
down_revision = '1c895164b7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
